apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::903541343477:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::903541343477:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OP6IT8NYHBH8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-04T17:55:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1204"
  uid: aa1c49fc-9658-4bf4-9189-a66fdcd557ba
